spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///testdb?useSSl=true
    username: root
    password: 1234
  application:
    name: provider
  cloud:
    zookeeper:
      connect-string: 192.168.1.191:2181
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    com.cloud.demo.microprovider.mapper: debug
