server:
  port: 8081
spring:
  cloud:
    zookeeper:
      connect-string: 192.168.1.191:2181
      discovery:
        register: false

provider:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
